app = "orlandoflores"
primary_region = "scl"  # Santiago, Chile

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[services]
  [[services.http_checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/"
    protocol = "http"
    timeout = "5s"
    tls_skip_verify = false

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[metrics]
  port = 8080
  path = "/metrics"

[deploy]
  strategy = "rolling"

[processes]
  app = "npm run start"

[experimental]
  auto_rollback = true

[scale]
  min = 1
  max = 1
  memory = "256mb"
  cpu = "shared"
  concurrency = 25
  hard_limit = 100
  soft_limit = 50
  force_https = true 